# Five Basic Tensor Operations

### This notebook is submitted for the partial fulfillment for the FreeCodeCamp Course: [Deep Learning with PyTorch: Zero to GANs](https://jovian.ml/forum/c/pytorch-zero-to-gans/18)

The chosen functions are: 
- resize_
- argmin
- index_add_
- triu
- triangular_solve

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.resize_

`resize_(*sizes, memory_format=torch.contiguous_format) → Tensor`

This function resizes a tensor to the specified size. If the specified size is too small, the new tensor will remove some elements. If the specified size is too large, the tensor will not initialize the remaining empty element slots

<h3> Example 1 - specified *size can accomodate all elements </h3>

In [2]:
a = torch.tensor([[1., 2., 7.], [3., 4., 0.], [5., 6., 14.], [7., 8., 10.]])
print("Original tensor: \n", a)
print("\nOriginal tensor shape: ", a.shape)

b = a.resize_(6,2)
print("\nResized tensor: \n", b)
print("\nResized tensor shape: ", b.shape)

Original tensor: 
 tensor([[ 1.,  2.,  7.],
        [ 3.,  4.,  0.],
        [ 5.,  6., 14.],
        [ 7.,  8., 10.]])

Original tensor shape:  torch.Size([4, 3])

Resized tensor: 
 tensor([[ 1.,  2.],
        [ 7.,  3.],
        [ 4.,  0.],
        [ 5.,  6.],
        [14.,  7.],
        [ 8., 10.]])

Resized tensor shape:  torch.Size([6, 2])


In the above example, a tensor, `a`, has 12 elements and is of shape 4x3.
<br>
The new tensor, `b`, is obtained by resizing `a` into a 6x2 tensor = 12 elements

<h3> Example 2 - specified *size exceeds the number of elements </h3>

In [3]:
a = torch.tensor([[1.], [3.], [5.], [7.]])
print("Original tensor: \n", a)
print("\nOriginal tensor shape: ", a.shape)

b = a.resize_(2,4)
print("\nResized tensor: \n", b)
print("\nResized tensor shape: ", b.shape)

Original tensor: 
 tensor([[1.],
        [3.],
        [5.],
        [7.]])

Original tensor shape:  torch.Size([4, 1])

Resized tensor: 
 tensor([[1.0000e+00, 3.0000e+00, 5.0000e+00, 7.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

Resized tensor shape:  torch.Size([2, 4])


In the above example, a tensor, `a`, has 4 elements and is of shape 4x1.
<br>
The new tensor, `b`, is obtained by resizing `a` into a 2x4 tensor. As `b` can contain 8 elements, the remaining 4 elements are initialized to 0.

<h3> Example 3 - specified *size is lower than the number of elements </h3>

In [4]:
a = torch.tensor([[1., 2., 7.], [3., 4., 0.], [5., 6., 14.], [7., 8., 10.]])
print("Original tensor: \n", a)
print("\nOriginal tensor shape: ", a.shape)
print("\nNumber of elements: ", a.numel())

b = a.resize_(5,2)
print("\nResized tensor: \n", b)
print("\nResized tensor shape: ", b.shape)
print("\nNumber of elements: ", b.numel())

Original tensor: 
 tensor([[ 1.,  2.,  7.],
        [ 3.,  4.,  0.],
        [ 5.,  6., 14.],
        [ 7.,  8., 10.]])

Original tensor shape:  torch.Size([4, 3])

Number of elements:  12

Resized tensor: 
 tensor([[ 1.,  2.],
        [ 7.,  3.],
        [ 4.,  0.],
        [ 5.,  6.],
        [14.,  7.]])

Resized tensor shape:  torch.Size([5, 2])

Number of elements:  10


In the above example, a tensor, `a`, has 12 elements and is of shape 4x3.
<br>
The new tensor, `b`, is obtained by resizing `a` into a 5x2 tensor. As `b` can contain 10 elements, the remaining last 2 elements of `a` are dropped.

`.resize_` should be used when there is a need to resize a tensor to a new specified dimension. <br>
This function doesn't usually break

## Function 2 - torch.argmin

`torch.argmin(input) → LongTensor`

This function returns the indices of the minimum value of all elements in the `input` tensor.

<br>

<h3> Example 1 - Returns the index of the minimum element in the whole tensor </h3>

In [5]:
# Generates a random tensor of size 5x6
a = torch.randn(5, 6)
print("Created tensor: \n", a)
print("Index of smallest element is: ", torch.argmin(a))

Created tensor: 
 tensor([[-0.1736,  0.0525, -0.0937, -0.9899, -1.7500,  0.3304],
        [-1.0819,  1.2164, -0.6724, -0.2279, -1.9529, -0.6846],
        [-1.0267,  0.0565,  1.0617, -1.2599,  0.0066,  0.3130],
        [-0.6138, -1.0320, -0.0042,  0.3454,  0.4859,  1.9801],
        [ 0.2410, -1.2258, -0.1671,  1.9748,  0.3232, -1.1991]])
Index of smallest element is:  tensor(10)


In [6]:
# Access the smallest element by index by resizing the index into a vector
b = a.resize_(1, a.numel())
print("Smallest element is: ", b[0][torch.argmin(a)])

Smallest element is:  tensor(-1.9529)


In the above sample, `torch.argmin(input_tensor)` is used to obtain the smallest element in the whole tensor, from the starting 0th element. From this, the tensor is resized to a vector and the smallest element is extracted. Alternatively, `torch.min(input_tensor)` can also be used

In [7]:
print("Smallest element is: ", torch.min(a))

Smallest element is:  tensor(-1.9529)


<h3> Example 2 (Breaking) - Only returns a single index when all the elements are the same value </h3>

In [8]:
a = torch.tensor([[1., 5., 1.], [3., 1., 7.]])
torch.argmin(a)

tensor(4)

When there are multiple elements with the same, minimum value, only a single index is returned. To rectify this, we can do another look and check all values which have the same minimum value.

In [9]:
min_value = a.resize_(1, a.numel())[0][torch.argmin(a)]
print ((a == min_value.item()).nonzero())

tensor([[0, 0],
        [0, 2],
        [0, 4]])


In the above example, the min_value is first obtained. Following which, `min_value.item()` is used to obtain the number itself from the 1-D tensor, which is used for comparison. <br>
The index of all the elements which has the minimum value is then returned in the subsequent tensor

Closing comments about when to use this function

## Function 3 - ???

Add some explanations

In [10]:
# Example 1 - working

Explanation about example

In [11]:
# Example 2 - working

Explanation about example

In [12]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 4 - ???

Add some explanations

In [13]:
# Example 1 - working

Explanation about example

In [14]:
# Example 2 - working

Explanation about example

In [15]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 5 - ???

Add some explanations

In [16]:
# Example 1 - working

Explanation about example

In [17]:
# Example 2 - working

Explanation about example

In [18]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [19]:
# !pip install jovian --upgrade --quiet

In [20]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
