> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Assignment 2 - Numpy Array Operations


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [21]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.empty
function2 = np.flip
function3 = np.diag
function4 = np.digitize
function5 = np.random.choice

## Function 1 - np.empty

Returns an array of uninitialized values

```np.empty(shape, dtype=float, order='C')```

In [4]:
# Example 1 - working 
arr1 = np.empty((3,3))
arr2 = np.empty((3,3))

print("First array: \n", arr1)
print("Second array: \n", arr2)

First array: 
 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.24498976e-321]
 [0.00000000e+000 0.00000000e+000 1.14688202e-311]]
Second array: 
 [[8.62437509e-288 5.43929112e-077 2.25755248e-231]
 [8.87698072e+247 4.24512632e+175 8.62437548e-288]
 [3.15421458e+161 7.20218835e+252 1.08490188e-312]]


An array of uninitialized values are returned. The array elements are really small and randomized each time.

In [8]:
# Example 2 - working
arr3 = np.zeros((3,3))
print(arr3 - arr2)
print(arr3 - arr1)

[[-8.62437509e-288 -5.43929112e-077 -2.25755248e-231]
 [-8.87698072e+247 -4.24512632e+175 -8.62437548e-288]
 [-3.15421458e+161 -7.20218835e+252 -1.08490188e-312]]
[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -6.24498976e-321]
 [ 0.00000000e+000  0.00000000e+000 -1.14688202e-311]]


The uninitialized values are pretty close to 0. 

### Comparison with np.zeroes

In [49]:
%timeit np.zeros(1000000)

85.7 µs ± 566 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [50]:
%timeit np.empty(1000000)

85.2 µs ± 318 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


np.empty should only be used when we want an array but do not care what values is inside. It is slightly faster than np.zeroes.

## Function 2 - np.flip

Reverses the order of elements in an array along the given axis.

```np.flip(m, axis=None)[source]```

In [62]:
# Example 1 - working
a = np.reshape(np.array([range(0, 25)]), (5,5))
print("Original matrix: \n", a)

b = np.flip(a, axis = None)
print("\nReversed order: \n", b)

b = np.flip(a, axis = 1)
print("\nReversed order for each row: \n", b)

Original matrix: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Reversed order: 
 [[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]

Reversed order for each row: 
 [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]


The function can reverse the elements within an array, depending on the supplied `axis` argument.

In [63]:
# Example 3 - breaking (to illustrate when it breaks)
b = np.flip(a, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

Example breaks as the chosen axis is out of bounds. Please choose an axis that is within the bounds.

## Function 3 - np.diag

Can be used to extract or construct a diagonal array. 

`numpy.diag(v, k=0)`

v: If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

k: Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

In [70]:
# Example 1 - Extracting the diagonals
a = np.arange(25).reshape((5,5))
print("Original matrix: \n", a)

print("\nDiagonals: \n", np.diag(a))

print("\nOne row below diagonal: \n", np.diag(a, -1))

Original matrix: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Diagonals: 
 [ 0  6 12 18 24]

One row below diagonal: 
 [ 5 11 17 23]


In the example, the diagonals are accessed from the 5x5 matrix. The function can also be used to retrieve diaognals that are not the main diagonals.

In [75]:
# Example 2 - Creating a matrix using np.diag
n = np.diag([1, 2, 3, 4, 5], k = 0)
n

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

A matrix with 0s is created with the inserted diagonal values. k can be adjusted to select non-diagonal elements. 

In [101]:
# Example 3 - breaking (to illustrate when it breaks)
np.diag([47, 10, 1], k = 100000)

MemoryError: Unable to allocate 37.3 GiB for an array with shape (100003, 100003) and data type int32

`np.diag` does not check if the argument `k` is a sensible number. It will automatically allocate a matrix to acomodate. Hence, care should be taken to ensure `k` is a sensible number.

This function is useful for extracting the diagonals, such as during eigne-value decomposition. 

## Function 4 - np.digitize

Return the indices of the bins to which each value in input array belongs.

`numpy.digitize(x, bins, right=False)`

x: array to be binned

bins: array of bins

right: indicates if the bins include the right edge. Default is False

In [104]:
# Example 1 - working
a = np.array([0.1, 0.9, 3.0, 1.6, 5.1, 6.8, 200.5])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
indexes = np.digitize(a, bins)
indexes

array([1, 1, 3, 2, 4, 4, 5], dtype=int64)

The index of which bin does the `a` element values fall in are given,

In [105]:
# Example 2 - breaking (to illustrate when it breaks)
a = np.array([0.1, 0.9, 3.0, 1.6, 5.1, 6.8, 200.5])
bins = np.array([10.0, 1.0, 2.5, 4.0, 0.0])
indexes = np.digitize(a, bins)

ValueError: bins must be monotonically increasing or decreasing

`np.digitize` assumes that the bins are arranged in monotonically increasing or decreasing order. 

To rectify this, we can order the bins array before calling `np.digitize`.

In [107]:
a = np.array([0.1, 0.9, 3.0, 1.6, 5.1, 6.8, 200.5])
bins = np.array([10.0, 1.0, 2.5, 4.0, 0.0])
bins = np.sort(bins)
indexes = np.digitize(a, bins)

print("Sorted bins: \n", bins)
indexes

Sorted bins: 
 [ 0.   1.   2.5  4.  10. ]


array([1, 1, 3, 2, 4, 4, 5], dtype=int64)

This function is useful for discretizing continous data. 

## Function 5 - np.random.choice

Generates a random sample from a given array

`np.random.choice(a, size=None, replace=True, p=None)`

a: array or int. If int, a random sample is generated from np.arange(a)

size: size of the sample required. Can be an int or tuple of ints

replace: Boolean, if sampling is done with replacement

p: The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution over all entries in a.

In [117]:
# Example 1 - working
np.random.choice(10, 15, replace = True)

array([2, 0, 4, 1, 6, 0, 9, 4, 6, 6, 4, 1, 0, 4, 2])

An array of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] is created. 15 samples are drawm without replacement. 

In [128]:
# Example 2 - working
a = np.array(range(20))
normalized_a = (a / np.sum(a))
np.random.choice(a, 20, replace = True, p = np.flip(normalized_a))

array([ 8,  5,  3,  4,  0,  0, 11,  1,  9,  7, 13,  4,  1, 16,  0,  1,  3,
        0,  0, 11])

In [134]:
print("Probability assignments: \n", np.flip(normalized_a))

Probability assignments: 
 [0.1        0.09473684 0.08947368 0.08421053 0.07894737 0.07368421
 0.06842105 0.06315789 0.05789474 0.05263158 0.04736842 0.04210526
 0.03684211 0.03157895 0.02631579 0.02105263 0.01578947 0.01052632
 0.00526316 0.        ]


In the above example, an array is created up to 20. The associated probabilities are reversed ie `0` has the highest probability while `20` has the lowest probabiity. 

Notice that there are a lot of sampled elements lower than 10. 

In [135]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array(range(20))
# normalized_a = (a / np.sum(a))
np.random.choice(a, 20, replace = True, p = a)

ValueError: probabilities do not sum to 1

Take note that when assigning probabilities, the sum must be one. A quick fix is to just take the weights with respect to the sum of the array ie

`normalized_a = (a / np.sum(a))`

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'